const GUIDE={
es:[
 ["🏠","Inicio","Arriba ves tu racha de días seguidos (🔥), tus puntos de experiencia (⭐), las medallas que llevas (🏅) y la barra de nivel. En «Hoy» tienes tres propuestas que cambian cada día: el reto del día, el deporte del día de la Enciclopedia y una curiosidad de «Tal día como hoy». Más abajo aparecen los temas del curso con el porcentaje que llevas de cada uno."],
 ["☀️","Reto del día","Reúne una prueba de cada tipo sacada de los temas publicados y da el doble de puntos. Es distinto cada día, así que conviene hacerlo a diario para mantener la racha."],
 ["📅","Tal día como hoy","Cada día del año tiene una curiosidad de historia del deporte con su fuente. Con los botones de día anterior y día siguiente puedes recorrer el calendario entero."],
 ["📚","Temas","Cada tema se trabaja por modos. En las fichas está el manual de bolsillo, por apartados; el mapa ordena las ideas principales y secundarias; el análisis de imágenes plantea afirmaciones que se aceptan o se rechazan deslizando; el glosario repasa los términos clave; la cronología pide ordenar los hechos; en fuentes hay que reconocer de dónde procede un texto; relaciona empareja prácticas, grupos y funciones; mitos desmonta tópicos; las preguntas rápidas son un test con tiempo, y hay también vídeos y pódcast. Los temas con candado se abren a medida que avanza el curso."],
 ["▶️","Vídeos","Reúne los vídeos cortos de todos los temas y los reproduce al azar, uno detrás de otro, deslizando hacia arriba como en las redes sociales. En cada vídeo, «Saber más» amplía el contenido y «Test» plantea una pregunta sobre lo que acabas de ver."],
 ["🔎","Buscar","Busca a la vez en las fichas, la Enciclopedia, el glosario, la cronología y los vídeos. Basta con escribir tres letras; al tocar un resultado vas directamente a él."],
 ["📖","Enciclopedia","Recoge el origen y la historia de más de cuatrocientos deportes, de los olímpicos a los tradicionales y los más raros. Puedes buscar por nombre, saltar por letra con el índice de la derecha o pedir un deporte al azar con el dado. En cada deporte hay una foto, una breve explicación de qué es en los menos conocidos, cuándo y dónde nace, su historia, las fuentes y, si aparece en la asignatura, el enlace al tema. Los botones A− y A+ cambian el tamaño de la letra."],
 ["🎓","Examen","Explica cómo es el examen y cómo prepararlo, con indicaciones para el test, la pregunta de desarrollo y el comentario de imagen."],
 ["⭐","Puntos, racha y niveles","Cada acierto suma puntos de experiencia, y el reto del día los duplica. La racha cuenta los días seguidos que entras a estudiar. Con los puntos subes de nivel, del 1 al 100, y al completar cada modo de un tema ganas su medalla."],
 ["⚙️","Ajustes","Se abre con la rueda de la cabecera. Desde aquí cambias el idioma, instalas la app en el móvil y cierras la sesión, que borra el progreso guardado en ese dispositivo. Si encuentras un error en una ficha o en la Enciclopedia, el botón «Avisar de un error» prepara un correo para el profesor."]
],
en:[
 ["🏠","Home","At the top you see your streak of consecutive days (🔥), your experience points (⭐), the badges you have earned (🏅) and the level bar. «Today» offers three items that change every day: the daily challenge, the sport of the day from the Encyclopedia and a fact from «On this day». Further down are the course units with your progress in each one."],
 ["☀️","Daily challenge","It brings together one task of each kind from the published units and gives double points. It is different every day, so it is worth doing daily to keep your streak."],
 ["📅","On this day","Every day of the year has a sports history fact with its source. The previous day and next day buttons let you browse the whole calendar."],
 ["📚","Units","Each unit is studied through modes. The study sheets are the pocket manual, by section; the map sets out the main and secondary ideas; image analysis presents statements you accept or reject by swiping; the glossary reviews the key terms; the timeline asks you to put events in order; in sources you identify where a text comes from; match pairs practices, groups and functions; myths takes apart clichés; the quick quiz is a timed test, and there are also videos and a podcast. Locked units open as the course moves on."],
 ["▶️","Videos","It gathers the short videos from every unit and plays them at random, one after another, swiping up as on social media. On each video, «Learn more» expands the content and «Test» asks a question about what you have just watched."],
 ["🔎","Search","It searches the study sheets, the Encyclopedia, the glossary, the timeline and the videos at once. Three letters are enough; tapping a result takes you straight to it."],
 ["📖","Encyclopedia","It covers the origin and history of more than four hundred sports, from Olympic ones to traditional and rare ones. You can search by name, jump by letter with the index on the right or ask for a random sport with the dice. Each sport has a photo, a short explanation of what it is for the less known ones, when and where it began, its history, the sources and, if it appears in the course, a link to the unit. The A− and A+ buttons change the text size."],
 ["🎓","Exam","It explains what the exam is like and how to prepare it, with guidance for the multiple-choice test, the essay question and the image commentary."],
 ["⭐","Points, streak and levels","Every correct answer adds experience points, and the daily challenge doubles them. The streak counts the consecutive days you come in to study. Points take you up the levels, from 1 to 100, and completing each mode of a unit earns its badge."],
 ["⚙️","Settings","Open it with the gear in the header. Here you change the language, install the app on your phone and log out, which deletes the progress saved on that device. If you find a mistake in a study sheet or in the Encyclopedia, the «Report a mistake» button prepares an email to the lecturer."]
]};
function renderGuia(){
  const from=S.view.from||{name:"settings"}; const G=GUIDE[S.lang]||GUIDE.es;
  app.innerHTML=header(t("guide"),true)+`<main><div class="guia">${G.map(([i,h,x],j)=>`<details${j===0?" open":""}><summary><span class="gi">${i}</span>${esc(h)}</summary><p>${esc(x)}</p></details>`).join("")}</div></main>`;
  bindHeader(()=>nav({name:"settings",from:from.from||{name:"home"}}));
}
