const WORDS={
es:[
 {w:"JUEGO",t:1,d:"Para Popplow, junto con la danza, el subsuelo que sirve de soporte al movimiento humano."},
 {w:"DANZA",t:1,d:"Popplow la considera la primera expresión de la cultura física, con finalidad erótica, mágica o guerrera."},
 {w:"PESCA",t:1,d:"Actividad de subsistencia prehistórica con arpón, anzuelo, tridente, nasa o canoa; hoy se discute si la pesca es deporte."},
 {w:"CAZAR",t:1,d:"Con arco y flecha, azagaya, jabalina, honda o bumerán; que la caza fuera cosa solo de varones no está demostrado."},
 {w:"ARPON",t:1,d:"Útil de pesca prehistórico; en las sociedades de cazadores, ejercicios como el arpón o la jabalina servían para mejorar la caza."},
 {w:"CUEVA",t:1,d:"En la de Obłazowa (Polonia) apareció el bumerán más antiguo que se conoce, tallado en marfil de mamut."},
 {w:"MAMUT",t:1,d:"De su marfil está tallado el bumerán más antiguo conocido, hallado en la cueva de Obłazowa."},
 {w:"FEMUR",t:1,d:"Hueso cuya resistencia a la flexión cae de forma pronunciada entre el 5000 y el 2000 a. C., señal de menos actividad física."},
 {w:"RITMO",t:1,d:"Las huellas de Engare Sero muestran a catorce mujeres caminando juntas al mismo ritmo, a 1,5 m/s."},
 {w:"MARCA",t:1,d:"En el modelo del rendimiento, el cuerpo produce marcas, rankings y una pirámide con la élite en la cúspide."},
 {w:"ELITE",t:1,d:"La cúspide de la pirámide del rendimiento, el modelo del deporte de competición."},
 {w:"TRIBU",t:1,d:"El grupo cuya seguridad y continuidad garantizaban las actividades físicas adaptadas al entorno y a las costumbres colectivas."},
 {w:"CANOA",t:1,d:"Uno de los útiles de pesca prehistóricos, junto al arpón, el anzuelo, el tridente y la nasa."},
 {w:"TUMBA",t:2,d:"Las pinturas de las tumbas egipcias, como las de Beni Hasan, son la fuente principal sobre la lucha y los juegos."},
 {w:"LUCHA",t:2,d:"Una de las tres modalidades de combate practicadas en Egipto, junto a la esgrima con bastones (tahtib) y el boxeo."},
 {w:"PERSA",t:2,d:"Del antiguo Irán, cuya tradición de fuerza pervive en la zurkhaneh, con sus flexiones, mazas y giros."},
 {w:"TEBAS",t:2,d:"En su necrópolis occidental, la tumba de Kheruef representa hacia 1360 a. C. un combate de boxeo."},
 {w:"CARRO",t:2,d:"El carro de guerra fue una de las destrezas del faraón, junto a la doma de caballos, la caza y el tiro con arco."},
 {w:"SENET",t:2,d:"Juego de tablero del antiguo Egipto."},
 {w:"DIANA",t:2,d:"El faraón tiraba con arco sobre lingotes de cobre bruto, piezas que se usaban para comerciar en el Mediterráneo."},
 {w:"ARCOS",t:2,d:"El arco compuesto, más manejable en los carros de guerra, lanzaba flechas hasta 300 metros, frente a los 150 del simple."},
 {w:"JUSTA",t:2,d:"Nace del manejo de las pértigas con que se llevaban las barcas y de las competiciones de obreros al acabar una gran obra."},
 {w:"BRAZA",t:2,d:"Algunos autores han creído reconocer el crol y la braza en las representaciones egipcias, aunque otros lo discuten."},
 {w:"BOXEO",t:2,d:"Presencia marginal en Egipto; la única evidencia indiscutible es una escena de la tumba de Kheruef, en Tebas."},
 {w:"MAZAS",t:2,d:"Piezas de madera que en la zurkhaneh se voltean por detrás de los hombros, siguiendo el ritmo del tambor."},
 {w:"NUBIA",t:2,d:"Tierra de origen del rey Taharqa, cuya estela aporta una de las evidencias de la carrera de fondo."},
 {w:"LUXOR",t:2,d:"Junto a ella, en Medamud, una inscripción del santuario de Montu narra los tiros con arco de Amenofis II."},
 {w:"NADAR",t:2,d:"En un pueblo fluvial nadaban barqueros y pescadores; nadar era destreza de élite si se aprendía con instructor."}
],
en:[
 {w:"GAMES",t:1,d:"For Popplow, together with dance, the ground that supports human movement."},
 {w:"DANCE",t:1,d:"Popplow sees it as the first expression of physical culture, with an erotic, magical or warlike purpose."},
 {w:"CAVES",t:1,d:"Obłazowa cave in Poland yielded the oldest known boomerang, carved from mammoth ivory."},
 {w:"IVORY",t:1,d:"The oldest known boomerang, found in Obłazowa cave, is carved from mammoth ivory."},
 {w:"FEMUR",t:1,d:"A bone whose bending strength falls sharply between 5000 and 2000 BC, a sign of less physical activity."},
 {w:"TRIBE",t:1,d:"The group whose safety and continuity physical activities, adapted to the setting and shared customs, helped to secure."},
 {w:"CANOE",t:1,d:"One of the prehistoric fishing tools, along with the harpoon, hook, trident and fish trap."},
 {w:"TRAPS",t:1,d:"One of the prehistoric strategies for hunting and fishing, alongside pursuit, stalking and ambush."},
 {w:"MARKS",t:1,d:"In the performance model, the body produces marks, rankings and a pyramid with the elite at the top."},
 {w:"ELITE",t:1,d:"The top of the performance pyramid, the model of competitive sport."},
 {w:"TOMBS",t:2,d:"Egyptian tomb paintings, such as those at Beni Hasan, are the main source on wrestling and games."},
 {w:"SENET",t:2,d:"A board game of ancient Egypt."},
 {w:"NUBIA",t:2,d:"Homeland of King Taharqa, whose stela is one of the pieces of evidence for long-distance running."},
 {w:"MACES",t:2,d:"Wooden clubs swung behind the shoulders in the zurkhaneh, following the beat of the drum."},
 {w:"JOUST",t:2,d:"It grew out of handling the poles used to move boats and out of workers' contests held when a great building was finished."},
 {w:"ARROW",t:2,d:"The composite bow, easier to handle on war chariots, shot arrows up to 300 metres, against 150 for the simple bow."},
 {w:"INGOT",t:2,d:"The pharaoh shot at targets made of raw copper ingots, pieces traded across the Mediterranean."},
 {w:"CRAWL",t:2,d:"Some authors have seen the crawl and breaststroke in Egyptian images, though others dispute it."},
 {w:"BOXER",t:2,d:"Boxing was marginal in Egypt; the only undisputed evidence is a scene in the tomb of Kheruef at Thebes."},
 {w:"LUXOR",t:2,d:"Near it, at Medamud, an inscription in the shrine of Montu tells of Amenhotep II's archery."},
 {w:"BOATS",t:2,d:"Handling the poles that moved the boats is one of the origins of the Egyptian joust."}
]};
